### ISSUE TITLE
Add repository to hub.helm.sh

### ISSUE THREAD

**Issue by bdashrad** [PrivateBin/helm-chart#3]
Now that we have a working helm chart and repository, we should add it to the [helm hub](https://hub.helm.sh/) to make it easier for other kubernetes users to find. Instructions are here: https://github.com/helm/hub/blob/master/Repositories.md

**Comment by elrido** [comment]
I have forked their repo in order to prepare the change in it, you find it at:
https://github.com/PrivateBin/hub
(we can delete it again, after the change gets merged)

I chose our default support@ mail-alias. If you would like to get mails from helm as well, I can either create a new dedicated mail alias that forwards to support@ and your email or you can add yourself as a maintainer in the `repos.yaml`.

I just discovered the github team feature and it could make management of the access to the various projects easier to manage, so I have invited you to that "Helm" team and gave it access to that fork, so you can change it and raise the PR to the helm hub, if you want.

**Comment by bdashrad** [comment]
since I watch this repo, I'll see any issue raised here. Feel free to open a new issue if anything comes into the support@ address if you think I can help.

**Comment by bdashrad** [comment]
@elrido can you complete the [DCO](https://probot.github.io/apps/dco/), the helm project requires signed commits. Instructions are here: https://github.com/helm/hub/pull/103/checks?check_run_id=141452591

**Comment by elrido** [comment]
Done
