### ISSUE TITLE
ReadWriteMany AccessMode unsupported for PVCs on GCP/GKE when deploying with Helm

### ISSUE THREAD

**Issue by christidis** [PrivateBin/helm-chart#56]
AccessMode is set to `ReadWriteMany` since PR https://github.com/PrivateBin/helm-chart/pull/18
```
    spec:
      accessModes: [ "ReadWriteMany" ]
...
```

If RWMany is required maybe it would make sense to note in the documentation that `ReadWriteMany` for storage backend is required (e.g. NFS), or think about a different option like using object storage somehow (eg filestore).

**What steps did you take and what happened:**
When creating a StatefulSet kind with standard storageClass, it fails on GCP with this error:
```
Failed to provision volume with StorageClass "standard": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce ReadOnlyMany] are supported
```

**What did you expect to happen:**
The PVC to be created without errors.

**Environment:**
Kubernetes version: (use kubectl version): client: `v1.21.1`, server: `v1.20.10-gke.1600`

**Workaround**
I had to create and manage the PVC separately with accessmode `ReadWriteOnce` in order to successfully use persistency. PrivateBin replicas is set to 1.
```
$ cat privatebin-pvc.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-privatebin-0
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem

$ kubectl -n privatebin apply -f privatebin-pvc.yaml 
persistentvolumeclaim/storage-privatebin-0 created
```

**Comment by bdashrad** [comment]
we can make this configurable from the values.yaml

**Comment by elrido** [comment]
We can make this configurable for sure. The application does expect a ReadWriteMany backend, though.

In the development version of the software (not yet released, no schedule yet), we have migrated the remaining filesystem-only persistence items (server salt, traffic limiter, purge limiter) into the data abstraction, so that instances configured for database storage or google cloud storage can run without needing any filesystem storage. We have [already prepared separate images](https://github.com/PrivateBin/docker-nginx-fpm-alpine#image-variants) (including one with the pretty large GCS libraries) but they currently still contain the stable release (1.3.5) which does still require a filesystem storage and has no GCS support.
